stages:
- name: compile
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/core/sdk:2.2-stretch
      shellScript: dotnet build
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./WebApplication1/Dockerfile
      buildContext: .
      tag: rekrut/web:prod
      registry: 127.0.0.1:34171
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
