stages:
- name: compile
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/core/sdk:2.2-stretch
      shellScript: dotnet build
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./WebApplication1/Dockerfile
      buildContext: .
      tag: ldy985/rekrut:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    when:
      branch:
        include:
        - master
        - develop
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.${CICD_GIT_BRANCH}.yaml
    when:
      branch:
        include:
        - master
        - develop
timeout: 60
notification: {}
