stages:
- name: compile
  steps:
  - runScriptConfig:
      image: mcr.microsoft.com/dotnet/core/sdk:2.2-stretch
      shellScript: dotnet build
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./WebApplication1/Dockerfile
      buildContext: .
timeout: 60
notification: {}
