kind: Service
apiVersion: v1
metadata:
  name: ${CICD_GIT_REPO_NAME}-service
spec:
  selector:
    app: webserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ${CICD_GIT_REPO_NAME}
        image: ${CICD_IMAGE}:prod-${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${CICD_GIT_REPO_NAME}-ingress
spec:
  rules:
  - host: xip.io
    http:
      paths:
      - backend:
          serviceName: ${CICD_GIT_REPO_NAME}-service
          servicePort: 80